# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                     #
#     _____  _     _    _  _____ _____ _   _          _____ _____     #
#    |  __ \| |   | |  | |/ ____|_   _| \ | |   /\   |  __ \_   _|    #
#    | |__) | |   | |  | | |  __  | | |  \| |  /  \  | |__) || |      #
#    |  ___/| |   | |  | | | |_ | | | | . ` | / /\ \ |  ___/ | |      #
#    | |    | |___| |__| | |__| |_| |_| |\  |/ ____ \| |    _| |_     #
#    |_|    |______\____/ \_____|_____|_| \_/_/    \_\_|   |_____|    #
#                                                                     #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# OFF     - no messages will be logged
# SEVERE  - all messages greater or equal to level 1000 will be logged
# WARNING - all messages greater or equal to level 900 will be logged
# INFO    - all messages greater or equal to level 800 will be logged
# CONFIG  - all messages greater or equal to level 700 will be logged
# FINE    - all messages greater or equal to level 500 will be logged
# FINER   - all messages greater or equal to level 400 will be logged
# FINEST  - all messages greater or equal to level 300 will be logged
# ALL     - all messages will be logged
logging-level: ALL

# the settings required to connect to a mysql server
mysql:
  # when enabled the api will attempt to connect to the specified mysql server
  enabled: false
  # the credentials of the mysql server
  credentials:
    # the url the mysql server is running on
    url: 127.0.0.1
    # the port the mysql server is running on
    port: 3306
    # the username to login as on the mysql server
    username: USERNAME
    # the password of the user to login as on the mysql server
    password: PASSWORD

# the settings to use when no mysql connection is established
non-mysql:
  # when enabled the api will force to use these settings disregarding any mysql connection
  force: true
  # the prefix
  prefix: §lMyAwesomePlugin
  # the chat color
  chat-color: GRAY
  # the message to display when performing an action without the required permissions
  player-no-permission-error-message: §l§cFEHLER! §r§cDafür hast du keine Rechte!
  # the message to display when executing a command that can only be executed by a player
  only-player-command-error-message: §l§cFEHLER! §r§cDieser Command kann nur durch einen Spieler ausgeführt werden!
  # the message to display when an error occurs while executing a command
  command-error-message: §l§cFEHLER! §r§cCommand konnte nicht ausgeführt werden!
  # the message to display when while executing a command has been given invalid args
  command-invalid-args-error-message: §l§cFEHLER! §r§cUngültige Command Argumente!
  # the message to display when an internal error occurs while executing a command
  command-internal-error-message: §l§cFEHLER! §r§cInterner Fehler beim Ausführen des Commands!